### ISSUE TITLE
Bug:点击保存无响应

### ISSUE THREAD

**Issue by Jonnyan404** [PasteUs/PasteMeLite#13]
- docker构建基于此[dockerfile](https://github.com/PasteUs/PasteMeLite/blob/master/Dockerfile)
- 前端和后端全部基于最新代码

### 问题
1. 点击保存,数据post成功,但前台无任何响应和跳转.

**Comment by Jonnyan404** [comment]
另外有个使用场景:就是部署此服务的机器,后续可能完全屏蔽网络访问权限.

**Comment by Jonnyan404** [comment]
然后我是想构建一个arm平台的来用,但是现在我没办法自己来构建.orz...

**Comment by LucienShui** [comment]
> * docker构建基于此[dockerfile](https://github.com/PasteUs/PasteMeLite/blob/master/Dockerfile)
> * 前端和后端全部基于最新代码
> 
> ### 问题
> 1. 点击保存,数据post成功,但前台无任何响应和跳转.

可以访问吗？构建时候有执行 `git submodule update --init --recursive` 吗？

> 然后我是想构建一个arm平台的来用,但是现在我没办法自己来构建.orz...

构建的时候报错是什么？上面不是说构建成功了吗？
可以考虑直接在 arm 下编译二进制文件，命令参考 [PasteUs/PasteMeLite@release-v0.0.3/.github/workflows/upload-to-release.yml](https://github.com/PasteUs/PasteMeLite/blob/release-v0.0.3/.github/workflows/upload-to-release.yml)。

**Comment by Jonnyan404** [comment]
> > * docker构建基于此[dockerfile](https://github.com/PasteUs/PasteMeLite/blob/master/Dockerfile)
> > * 前端和后端全部基于最新代码
> > 
> > ### 问题
> > 
> > 1. 点击保存,数据post成功,但前台无任何响应和跳转.
> 
> 可以访问吗？构建时候有执行 `git submodule update --init --recursive` 吗？
> 
> > 然后我是想构建一个arm平台的来用,但是现在我没办法自己来构建.orz...
> 
> 构建的时候报错是什么？上面不是说构建成功了吗？

这个我描述问题,可以构建成功,构建成功后,就是点击保存无效.

**Comment by LucienShui** [comment]
> 另外有个使用场景:就是部署此服务的机器,后续可能完全屏蔽网络访问权限.

只要访问网站的电脑有网络就不影响使用，CDN 是在浏览器端进行加载的。

**Comment by Jonnyan404** [comment]
可以访问吗？构建时候有执行 git submodule update --init --recursive 吗？
@LucienShui 这个在哪一步执行?

**Comment by LucienShui** [comment]
> > 可以访问吗？构建时候有执行 git submodule update --init --recursive 吗？
>
> @LucienShui 这个在哪一步执行?

构建或编译之前，用来拉前后端的源代码。

**Comment by Jonnyan404** [comment]
> > > 可以访问吗？构建时候有执行 git submodule update --init --recursive 吗？
> > 
> > 
> > @LucienShui 这个在哪一步执行?
> 
> 构建或编译之前，用来拉前后端的源代码。

好吧,我是手动去 git clone 的

**Comment by LucienShui** [comment]
> > > > 可以访问吗？构建时候有执行 git submodule update --init --recursive 吗？
> > > 
> > > 
> > > @LucienShui 这个在哪一步执行?
> > 
> > 
> > 构建或编译之前，用来拉前后端的源代码。
> 
> 好吧,我是手动去 git clone 的

以及，arm 平台貌似需要用 arm 平台的镜像。不行就试试二进制编译吧，我 update 了一下之前的 comment，可以看看。

**Comment by Jonnyan404** [comment]
> > > > > 可以访问吗？构建时候有执行 git submodule update --init --recursive 吗？
> > > > 
> > > > 
> > > > @LucienShui 这个在哪一步执行?
> > > 
> > > 
> > > 构建或编译之前，用来拉前后端的源代码。
> > 
> > 
> > 好吧,我是手动去 git clone 的
> 
> 以及，arm 平台貌似需要用 arm 平台的镜像。不行就试试二进制编译吧，我 update 了一下之前的 comment，可以看看。

ok

**Comment by LucienShui** [comment]
https://github.com/LucienShui/PasteMe/issues/92
